### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by abelbriggs1** [Semx11/Autotip#11]
Hi,

First of all, very useful mod. Thanks for maintaining it.

I was looking to build the code myself, but I'm not particularly familar with Gradle, and so I've been having trouble with building the repo (IntelliJ can't seem to download the Google/Forge dependencies properly, for some reason). I was wondering if you had any build instructions.

Thanks.

**Comment by Semx11** [comment]
Hey, sorry for the late reply.

Instructions for IntelliJ should be as follows:

### Setting up the ForgeGradle workspace

1. Run `git clone` to clone the repo onto your computer
2. Start IntelliJ, open project, browse to the repo you just cloned, and open the `build.gradle` file as a project
3. In the window that pops up ("Import Project from Gradle"), do the following: ([image](https://i.imgur.com/HPZVO5Q.png))
  a. Tick the option "Use auto-import"
  b. Tick the option "Use default gradle wrapper" OR "Use gradle 'wrapper' task configuration" (both should work)
  c. Press OK
4. Open the Gradle tool window on the right side, and navigate to the task `setupDecompWorkspace` in `Tasks > forgegradle` ([image](https://i.imgur.com/maKStku.png))
5. Right-click the task `setupDecompWorkspace` and click on `Create '... [setupDecomp...'...` ([image](https://i.imgur.com/HvMHxiw.png))
6. In the window that opens, set the `VM options` to `-Xmx2G -Xms2G`. If you have at least 8 GB of RAM, I recommend using 4 GB (`-Xmx4G -Xms4G`). Then, press OK. ([image](https://i.imgur.com/1I6T7eF.png))
7. Run the task you just created at the top-right side of your screen by pressing the play button, and wait for it to finish. ([image](https://i.imgur.com/AKV1ll2.png))

### Building the mod

1. In the Gradle tool window, navigate to `Tasks > build > build`. Right-click it, and run it. ([image](https://i.imgur.com/fYz3h0y.png))
2. When the task is finished, you can find the compiled .jar file in the folder `build/libs`. By default, it should be called `Autotip-3.0.jar`. This is the file you can put in your `mods` folder. ([image](https://i.imgur.com/NQVs1z0.png))

### Running the Minecraft client inside the development environment (optional)

1. Run the task `genIntellijRuns` inside the Gradle tool window. You don't need to create a task for it, you can run it directly by right-clicking and pressing the play button next to "Run". ([image](https://i.imgur.com/LGK5DZ2.png))
2. After running `genIntellijRuns`, two new Run configuration should appear in the dropdown. Expand the dropdown and click on `Edit configurations...` ([image](https://i.imgur.com/t6m2OBc.png))
3. Inside the Run/Debug configurations window, select the `Minecraft Client` configuration under `Application`. Then look for the option `Use classpath of module`, and change it to `Autotip.main` ([image](https://i.imgur.com/NZSEvCm.png)). 
4. For mods that also have a server-side part, do the same for the configuration `Minecraft Server`. This is not needed for Autotip, as it is a client-side mod.
5. If you want to run the client, select it from the dropdown at the top and press the Debug button. This will start a Minecraft client with a fake player. ([image](https://i.imgur.com/A1qVKIQ.png))
6. (optional) It is possible to authenticate yourself by editing the run configuration and adding the program arguments `--username=<email/username> --password=<password>`. ([image](https://i.imgur.com/vmMsNtO.png))

I hope this answers your question, even though it's 6 months late. If you have any issues while following these instructions, feel free to reply so I can help you resolve them.

Thank you!
