### ISSUE TITLE
bug feedback

### ISSUE THREAD

**Issue by guation** [Semx11/Autotip#12]
I'm Chinese,game in loading and collapse.

java.lang.NullPointerException: Unexpected error
	at me.semx11.autotip.event.impl.EventClientTick.onClientTick(EventClientTick.java:23)

[crash-2019-07-20_09.21.16-client.txt](https://github.com/Semx11/Autotip/files/3413141/crash-2019-07-20_09.21.16-client.txt)

Thanks.

**Comment by Semx11** [comment]
I need more information.

Start the game, make it crash/collapse, exit game, then send these two:
1. %appdata%\.minecraft\logs\latest.log
2. %appdata%\.minecraft\logs\fml-client-latest.log

Thanks.

**Comment by guation** [comment]
[crash-2019-07-22_11.50.18-client.txt](https://github.com/Semx11/Autotip/files/3415652/crash-2019-07-22_11.50.18-client.txt)
[latest.log](https://github.com/Semx11/Autotip/files/3415653/latest.log)
I can't find fml-client-latest.log.
It will crash when the game is Loading completed, and I guess it's related to my network in China.

**Comment by Semx11** [comment]
There are a lot of errors with your network, it can't connect to any websites that use HTTPS. This is required for Autotip as it has to communicate with our server.

If you use a VPN, make sure it can connect to HTTPS websites. Autotip will disable itself if it can't connect to our server.

**I have fixed the crash for you**, if you download it again from our website, you will get a working version: http://dl.autotip.pro/3.0

Hope this helps, and thank you for reporting!
