### ISSUE TITLE
ModCore Privacy

### ISSUE THREAD

**Issue by altrisi** [Semx11/Autotip#17]
So some versions ago (I tested 3.0) ModCore was introduced to be installed automatically from AutoTip, even though it was still optional to download the version with ModCore from the AutoTip website.

In the latest version (3.0.1), AutoTip with the ModCore installation is the only available download.
While I (may?) understand using ModCore, the fact is that it's actually sending data that haven't been told to be sent and that _may_ be a privacy concern since ModCore is actually distributing/publishing that data (the green circle in the tablist when someone in your server is using ModCore, for example).

While I've personally been able to see the way to disable it's installation by looking [into the code](https://github.com/Semx11/Autotip/blob/176c961ce899ee478dde5f85c7d4764b263f1a87/src/main/java/me/semx11/autotip/modcore/Tweaker.java#L25), users that only want to download the mod and don't have that knowledge don't have any easy way to disable it (or to know how to disable it).
There should be:

- Some place telling the data sent via ModCore and all the privacy stuff
- Either some page advising how to set the system variable to opt-out from ModCore for regular users or a simple toggle for the user to choose whether installing ModCore before it actually gets installed

I don't really know how this all (relatively) new privacy thing works, but I just find annoying getting unwanted things installed and wanted to let you know.
P.S.: Actually, there is no (or I can't find any) mention to ModCore in the AutoTip website now.

**Comment by Sk1er** [comment]
Hi,
Thank you for posting your concerns. The version of ModCore in AutoTip has not yet been activated and therefore currently does not do anything. All of the concerns mentioned above will be addressed in their entirety and made public prior to ModCore’s activation.
