### ISSUE TITLE
No xp/coins showing 

### ISSUE THREAD

**Issue by unstoppalezzz** [Semx11/Autotip#21]
when I was using your mod your mod and something strange happened it said I have received 0 xp / coins but when I when to my profile I gain xp 
![2020-07-15_16 40 17](https://user-images.githubusercontent.com/67549522/87597793-6b091800-c6c0-11ea-9aa5-467aa5413abf.png)
![2020-07-15_17 24 46](https://user-images.githubusercontent.com/67549522/87597797-6cd2db80-c6c0-11ea-8776-16bad809be0c.png)
![2020-07-15_16 57 23](https://user-images.githubusercontent.com/67549522/87597799-6e9c9f00-c6c0-11ea-8095-45228190ef71.png)

**Comment by Semx11** [comment]
This mod doesn't track XP gain, only the XP gained by sending and receiving tips. Hope that clears things up!
