### ISSUE TITLE
Autotip command executes on 'at' (no slash)

### ISSUE THREAD

**Issue by Chearful** [Semx11/Autotip#5]
Autotip should only be triggering on ``/at``, but it also triggers when my message starts with ``at``.

i.e. autotip prompts me for an actual autotip command argument when I try putting ``at least try`` in chat.

**Comment by minemanpi** [comment]
This is an issue with Forge, you can try it with any other Forge mod's command. We will probably add the option to disable the /at shortcut command in the future since it interferes with so many normal messages.

**Comment by minemanpi** [comment]
oh turns out forge version 1902 fixes this. just use that version and you're good

**Comment by Chearful** [comment]
https://i.thomas.gg/F2cw6CB.png

Issue still persists on 1902.

**Comment by minemanpi** [comment]
Interesting, Sem told me 1902 fixed it. I might make a coremod that fixes the issue in the future.

**Comment by Semx11** [comment]
@Chearful are you using a Mac by any chance?

**Comment by Chearful** [comment]
Windows 8.1.
